routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FarmasiController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JenisObatController;
use App\Http\Controllers\PenerimaanObatController;
use App\Http\Controllers\TransaksiGudangController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PolindesController;
use Illuminate\Auth\Events\Login;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/jenis-obat', JenisObatController::class);
Route::resource('/penerimaan-obat', PenerimaanObatController::class);
Route::resource('/obat', ObatController::class);
// Route::get('/obat/hapus/{name}','ObatController@hapus');
Route::resource('/dashboard', DashboardController::class);
Route::resource('/transaksi-gudang', TransaksiGudangController::class);
Route::get('/farmasi', [FarmasiController::class, 'index']);
Route::get('/farmasi/daftar-obat', [FarmasiController::class, 'index']);
Route::get('/farmasi/penerimaan-obat', [FarmasiController::class, 'penerimaanObat']);
Route::get('/farmasi/distribusi-obat', [FarmasiController::class, 'distribusiObat']);

//polindes
Route::get('/polindes', [PolindesController::class, "index"]);
Route::get('/polindes/{id}', [PolindesController::class, "show"]);

// Route Login
Route::get('/user/register', [UserController::class, 'register'])->name('register');
Route::post('/user/register', [UserController::class, 'register_action'])->name('register.action');
Route::get('/user/login', [UserController::class, 'login'])->name('login');
Route::post('/user/login', [UserController::class, 'login_action'])->name('login.action');
Route::get('/user/password', [UserController::class, 'password'])->name('password');
Route::post('/user/password', [UserController::class, 'password_action'])->name('password.action');
Route::get('/user/logout', [UserController::class, 'logout'])->name('logout');

app/Models/PenerimaanObat.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PenerimaanObat extends Model
{
    use HasFactory;
    protected $guarded = ['id'];
    protected $table = 't_penerimaan_obat';
    protected $fillable = [
        'sumber_dana',
        'tanggal',
        'keterangan',
    ];
    public function obats()
    {
        return $this->hasMany(Obat::class, 'penerimaan_obat_id', 'id');
    }
}

app/Http/Controllers/PenerimaanObatController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\PenerimaanObat;
use App\Models\Obat;
use App\Models\JenisObat;

class PenerimaanObatController extends Controller
{
    protected $obatModel;

    public function __construct(){
        $this->obatModel = new Obat();
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $penerimaanObats = $this->obatModel->with('jenisObat')->get();
        return view('penerimaan-obat/index', [
            'penerimaan_obats' => $penerimaanObats,
            'jenis_obats' => JenisObat::all(),
        ]);
    }
}

resources/views/penerimaan-obat/index.blade.php
@extends('layouts.master')
@section('content')
<div class="main">
  <!-- MAIN CONTENT -->
  <div class="main-content">
    <div class="container-fluid">
      <h3 class="page-title">Penerimaan Obat</h3>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Input Obat Masuk</button>
          <a class="btn btn-success" href="">Input Obat Masuk Dengan Excel</a>
          <a class="btn btn-warning" href="{{ route('jenis-obat.index') }}">Tambah Jenis Obat</a>
        </ol>
      </nav>
      <div class="row">
        <div class="col">
          <!-- BASIC TABLE -->
          <div class="panel panel-headline">
            <div class="panel-heading">
              <h1 class="panel-title">Tabel Penerimaan Obat</h1>
            </div>
            <div class="panel-body">
              <table class="table">
                <thead>
                  <tr>
                    <th>No</th>
                    <th>Sumber Dana </th>
                    <th>Nama Obat </th>
                    <th>Jenis Obat</th>
                    <th>Jumlah</th>
                    <th>Tanggal</th>
                    <th>Keterangan</th>
                    <th>Opsi</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($penerimaan_obats as $po)
                  <tr>
                    <th scope="row"></th>
                    <td>{{$po->sumber_dana}}</td>
                    <td>{{$po->name}}</td>
                    <td>{{$po->jenisObat->type}}</td>
                    <td>{{$po->jumlah}}</td>
                    <td>{{$po->tanggal}}</td>
                    <td>{{$po->keterangan}}</td>
                    <td>
                        <form action="/obat/{{$po->id}}" method="POST">
                          @csrf
                          <button class="button btn-danger btn btn-sm" onclick="return confirm('Are you sure?')">Hapus</button>
                          @method('DELETE')
                        </form>
                          <button class="button btn-warning btn btn-sm">Edit</button>
                    </td>
                  </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
          <!-- Modal -->
          <div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Penerimaan Obat</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                  <form method="post" action="/obat">
                    @csrf
                    <div class="form-group">
                      <label for="name" class="form-label">Nama Obat</label>
                      <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="form-group">
                      <label for="jenis-obat" class="form-label">Jenis Obat</label>
                      <select class="form-control" aria-label="Default select example" name="jenis_obat_id" id="jenis-obat">
                        @foreach ($jenis_obats as $jenis_obat)
                        @if ($jenis_obat->id==old('jenis_obat_id'))
                        <option value="{{$jenis_obat->id}}" selected>{{$jenis_obat->type}}</option>
                        @else
                        <option value="{{$jenis_obat->id}}">{{$jenis_obat->type}}</option>
                        @endif

                        @endforeach
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="jumlah" class="form-label">Jumlah</label>
                      <input type="text" class="form-control" id="jumlah" name="jumlah" required>
                    </div>
                    <div class="form-group">
                      <label for="tanggal_kadaluarsa" class="form-label">Tanggal Kadaluarsa</label>
                      <input type="date" class="form-control" id="tanggal_kadaluarsa" name="tanggal_kadaluarsa" required>
                    </div>

                    <div class="form-group">
                      <label for="satuan" class="form-label">Satuan</label>
                      <select class="form-control" aria-label="Default select example" id="satuan" name="satuan">
                        <option value="tablet">TABLET</option>
                        <option value="vial">VIAL</option>
                        <option value="ampul">AMPUL</option>
                        <option value="botol">BOTOL</option>
                        <option value="pcs">PCS</option>
                        <option value="paket">PAKET</option>
                        <option value="blister">BLISTER</option>
                        <option value="galon">GALON</option>
                        <option value="tub">TUB</option>
                        <option value="supp">SUPP</option>
                        <option value="kap">KAP</option>
                        <option value="pen">PEN</option>
                        <option value="sach">SACH</option>
                        <option value="softbag">SOFTBAG</option>
                        <option value="set">SET</option>
                        <option value="kit">KIT</option>
                        <option value="kotak">kotak</option>
                        <option value="pot">POT</option>
                        <option value="lt">LT</option>
                        <option value="tbg">TBG</option>
                        <option value="unit">UNIT</option>
                        <option value="kg">KG</option>
                        <option value="tes">TES</option>
                        <option value="bj">BJ</option>
                      </select>
                    </div>
                    <div class="form-group">
                      <label for="tanggal" class="form-label">Tanggal Penerimaan</label>
                      <input type="date" class="form-control" id="tanggal" name="tanggal" required>
                    </div>
                    <div class="form-group">
                      <label for="sumber_dana" class="form-label">Sumber Obat</label>
                      <select class="form-control" aria-label="Default select example" id="sumber_dana" name="sumber_dana">
                        <option value="APBD">APBD</option>
                        <option value="JKN">JKN</option>
                      </select>
                      <div class="form-group">
                        <label for="keterangan" class="form-label">Keterangan</label>
                        <input type="text" class="form-control" id="keterangan" name="keterangan" required>
                      </div>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                  </form>
                </div>
              </div>
            </div>
            @endsection