routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FarmasiController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\JenisObatController;
use App\Http\Controllers\PenerimaanObatController;
use App\Http\Controllers\TransaksiGudangController;
use App\Http\Controllers\ObatController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PolindesController;
use Illuminate\Auth\Events\Login;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('/jenis-obat', JenisObatController::class);
Route::resource('/penerimaan-obat', PenerimaanObatController::class);
Route::resource('/obat', ObatController::class);
// Route::get('/obat/hapus/{name}','ObatController@hapus');
Route::resource('/dashboard', DashboardController::class);
Route::resource('/transaksi-gudang', TransaksiGudangController::class);
Route::get('/farmasi', [FarmasiController::class, 'index']);
Route::get('/farmasi/daftar-obat', [FarmasiController::class, 'index']);
Route::get('/farmasi/penerimaan-obat', [FarmasiController::class, 'penerimaanObat']);
Route::get('/farmasi/distribusi-obat', [FarmasiController::class, 'distribusiObat']);

//polindes
Route::get('/polindes', [PolindesController::class, "index"]);
Route::get('/polindes/{id}', [PolindesController::class, "show"]);

// Route Login
Route::get('/user/register', [UserController::class, 'register'])->name('register');
Route::post('/user/register', [UserController::class, 'register_action'])->name('register.action');
Route::get('/user/login', [UserController::class, 'login'])->name('login');
Route::post('/user/login', [UserController::class, 'login_action'])->name('login.action');
Route::get('/user/password', [UserController::class, 'password'])->name('password');
Route::post('/user/password', [UserController::class, 'password_action'])->name('password.action');
Route::get('/user/logout', [UserController::class, 'logout'])->name('logout');

resources/views/layouts/_footer.blade.php
<footer>
	<div class="container-fluid">
		<p class="copyright">Made with <i class="lnr lnr-heart"></i><a href="https://bootstrapthemes.co">BootstrapThemes</a>
		</p>
	</div>
</footer>

resources/views/layouts/_navbar.blade.php
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="brand">
		<a href="index.html"><img src="/assets/img/logo-dark.png" alt="Klorofil Logo" class="img-responsive logo"></a>
	</div>
	<div class="container-fluid">
		<div class="navbar-btn">
			<button type="button" class="btn-toggle-fullwidth"><i class="lnr lnr-arrow-left-circle"></i></button>
		</div>
		<form class="navbar-form navbar-left">
			<div class="input-group">
				<input type="text" value="" class="form-control" placeholder="Search dashboard...">
				<span class="input-group-btn"><button type="button" class="btn btn-primary">Go</button></span>
			</div>
		</form>
		<div id="navbar-menu">
			<ul class="nav navbar-nav navbar-right">
				<!-- <li class="dropdown">
								<a href="#" class="dropdown-toggle icon-menu" data-toggle="dropdown">
									<i class="lnr lnr-alarm"></i>
									<span class="badge bg-danger">5</span>
								</a>
								<ul class="dropdown-menu notifications">
									<li><a href="#" class="notification-item"><span class="dot bg-warning"></span>System space is almost full</a></li>
									<li><a href="#" class="notification-item"><span class="dot bg-danger"></span>You have 9 unfinished tasks</a></li>
									<li><a href="#" class="notification-item"><span class="dot bg-success"></span>Monthly report is available</a></li>
									<li><a href="#" class="notification-item"><span class="dot bg-warning"></span>Weekly meeting in 1 hour</a></li>
									<li><a href="#" class="notification-item"><span class="dot bg-success"></span>Your request has been approved</a></li>
									<li><a href="#" class="more">See all notifications</a></li>
								</ul>
							</li> 
							 <li class="dropdown">
								<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="lnr lnr-question-circle"></i> <span>Help</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
								<ul class="dropdown-menu">
									<li><a href="#">Basic Use</a></li>
									<li><a href="#">Working With Data</a></li>
									<li><a href="#">Security</a></li>
									<li><a href="#">Troubleshooting</a></li>
								</ul>
							</li> -->
				@auth
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="assets/img/user.png" class="img-circle" alt="Avatar"> <span>{{ Auth::user()->name }}</span> <i class="icon-submenu lnr lnr-chevron-down"></i></a>
					<ul class="dropdown-menu">
						<li><a href="#"><i class="lnr lnr-user"></i> <span>Profil Saya</span></a></li>
						<!-- <li><a href="#"><i class="lnr lnr-envelope"></i> <span>Message</span></a></li> -->
						<li><a href="{{route('password')}}"><i class="lnr lnr-cog"></i> <span>Ganti Password </span></a></li>
						<li><a href="{{route('logout')}}"><i class="lnr lnr-exit"></i> <span>Keluar</span></a></li>
					</ul>
				</li>
				@endauth
		</div>
	</div>
</nav>

resources/views/layouts/_sidebar.blade.php
 <div id="sidebar-nav" class="sidebar">
     <div class="sidebar-scroll">
         <nav>
             <ul class="nav">
                 <li><a href="{{ route('dashboard.index') }}" class="active"><i class="lnr lnr-home"></i>
                         <span>Dashboard</span></a></li>
                 <li><a href="{{ route('penerimaan-obat.index') }}" class="active"><i class="fa fa-download"></i>
                         <span>Obat Masuk</span></a></li>
                 <li><a href="{{ route('obat.index') }}" class="active"><i class="fa fa-database"></i> <span>Gudang
                             Obat</span></a></li>
                 <li><a href="/transaksi-gudang" class="active"><i class="fa fa-database"></i>
                         <span>Transaksi Gudang</span></a></li>
                 <li><a href="/farmasi" class="active"><i class="fa fa-database"></i>
                         <span>Farmasi</span></a></li>
                 <li><a href="/polindes" class="active"><i class="fa fa-database"></i>
                         <span>Polindes</span></a></li>
                 <!-- <li><a href="#" class=""><i class="lnr lnr-cog"></i> <span>Panels</span></a></li> -->
             </ul>
         </nav>
     </div>
 </div>

resources/views/layouts/master.blade.php
<!doctype html>
<html lang="en">

<head>
    <title>MANAGEMENT OBAT</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <link rel="stylesheet" href="/assets/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/assets/vendor/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="/assets/vendor/linearicons/style.css">
    <link rel="stylesheet" href="/assets/vendor/chartist/css/chartist-custom.css">
    <link rel="stylesheet" href="/assets/css/main.css">
    <link rel="stylesheet" href="/assets/css/demo.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700" rel="stylesheet">
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/assets/img/favicon.png">
    <!-- CSS only -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous"> -->
    <!-- JavaScript Bundle with Popper -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous">
    </script> -->
    <style>
    </style>
</head>

<body>
    <div id="wrapper">
        @include('layouts._navbar')
        @include('layouts._sidebar')
        @yield('content')


        <div class="clearfix"></div>
        <footer>
            @include('layouts._footer')
        </footer>
    </div>
    <script src="/assets/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/vendor/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="/assets/vendor/jquery.easy-pie-chart/jquery.easypiechart.min.js"></script>
    <script src="/assets/vendor/chartist/js/chartist.min.js"></script>
    <script src="/assets/scripts/klorofil-common.js"></script>

</body>

@include('sweetalert::alert')

</html>